sudo: false
language: python
python:
  - "2.7"
addons:
  apt:
    packages:
      - gfortran
      - liblapack-dev
      - libblas-dev
      - ccache
services:
  - mongodb
# command to install dependencies
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache
before_install:
    - export PATH="/usr/lib/ccache:$PATH"
install:
  - "pip install -r requirements.txt"
# command to run tests
script: python tests.py
notifications:
  slack:
    rooms:
      - democracyclub:aiQoHSfNIxB9CSu1M9CAyqYi#mentions
